FROM ubuntu:20.04@sha256:bffb6799d706144f263f4b91e1226745ffb5643ea0ea89c2f709208e8d70c999

ARG use_apt_proxy="no"

ARG pip_index_url
ARG pip_index
ARG pip_index_host

ARG http_proxy
ARG https_proxy
ARG no_proxy="${no_proxy}"
ARG socks_proxy
ARG TZ="Asia/Ho_Chi_Minh"

ENV TERM=xterm \
    http_proxy=${http_proxy}   \
    https_proxy=${https_proxy} \
    no_proxy=${no_proxy} \
    socks_proxy=${socks_proxy} \
    LANG='C.UTF-8'  \
    LC_ALL='C.UTF-8' \
    TZ=${TZ} \
    DEBIAN_FRONTEND=noninteractive

ARG USER="lawrag"
ARG DJANGO_CONFIGURATION="production"
ENV DJANGO_CONFIGURATION=${DJANGO_CONFIGURATION}

RUN if [ "$use_apt_proxy" = "yes" ]; then \
    cp /etc/apt/sources.list.tmp /etc/apt/sources.list; \
    echo "USING APT REPOS: "; \
    cat /etc/apt/sources.list; \
fi

# Install necessary apt packages
RUN apt-get update && apt-get --no-install-recommends install -yq \
        apache2 \
        apache2-dev \
        libsasl2-dev \
        ca-certificates \
        libapache2-mod-xsendfile \
        libgeos-dev \
        libgomp1 \
        libgl1 \
        supervisor \
        libldap-2.4-2 \
        libsasl2-2 \
        libpython3-dev \
        tzdata \
        python3-distutils \
        p7zip-full \
        poppler-utils \
        curl \
        libglib2.0-0 \
        libsm6 \
        libxrender1 \
        libxext6 \
        python3.8 \
        python3-dev \
        python3-pip \
        python3-venv \
        gettext && \
    ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    rm -rf /var/lib/apt/lists/* && \
    echo 'application/wasm wasm' >> /etc/mime.types

# Install Helm
# RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 \
#     && chmod 700 get_helm.sh \
#     && ./get_helm.sh --version v3.11.2
# # Install kubectl
# RUN curl -fsSL -o kubectl https://dl.k8s.io/release/v1.21.1/bin/linux/amd64/kubectl \
#     && chmod +x kubectl \
#     && mv ./kubectl /usr/bin/kubectl
# # Install velero
# RUN curl -fsSL -o velero.tar.gz https://github.com/vmware-tanzu/velero/releases/download/v1.12.1/velero-v1.12.1-linux-amd64.tar.gz \
#     && tar -xzf velero.tar.gz \
#     && mv velero-v1.12.1-linux-amd64/velero /usr/bin/velero \
#     && rm -r velero-v1.12.1-linux-amd64 velero.tar.gz

# Install requirements
RUN if [ ! -z "$pip_index_url" ] ; then \
    pip config set global.index-url ${pip_index_url}; \
    pip config set global.index ${pip_index}; \
    pip config set global.trusted-host ${pip_index_host}; \
fi
COPY lawrag/requirements/ /tmp/requirements/

RUN pip install --no-cache-dir --upgrade pip==21.2.4 setuptools==59.8.0 wheel==0.37.1
RUN pip install --upgrade requests && pip install --no-cache-dir -r /tmp/requirements/${DJANGO_CONFIGURATION}.txt
RUN rm -rf /tmp/requirements/

# Add a non-root user
ENV HOME /home/${USER}
RUN adduser --shell /bin/bash --disabled-password --gecos "" ${USER}
ENV USER=${USER}
USER ${USER}

